#!/bin/sh

#
# simple wrapper for running a streamlit application with orderly logs
# This script is supposed to run in the background.
#
appname="show-all-config"
log_directory="logs"
logfile="$log_directory/$(date +"%Y-%m-%dT%H:%M:%S")-$appname.log"

# Create log directory if it doesn't exist
if  [ ! -d $log_directory ]; then
  mkdir -p "$log_directory"
fi

streamlit run "$appname.py" >$logfile 2>&1

