#!/bin/sh

#
# simple wrapper for running a streamlit application with orderly logs
# This script is supposed to run in the background.
#
appname="show-all-config"
logfile="logs/$(date --rfc-3339=seconds)-$appname.log"

streamlit run "$appname.py" >$logfile 2>&1

